"""Static catalog configuration for homepage sections."""

HOME_SECTIONS: list[dict[str, object]] = [
    {   'description': '厂商对产品安全、配置或策略的更新说明。',
    'slug': 'vendor_updates',
    'title': '厂商发布',
    'topics': [{'title': '厂商更新动态', 'topic': 'vendor-update'}]},
    {   'description': '媒体与安全团队对热点事件的报道。',
    'slug': 'security_news',
    'title': '安全新闻',
    'topics': [{'title': '新闻聚焦', 'topic': 'security-news'}]},
    {   'description': '社区、开源项目或团队的安全实践分享。',
    'slug': 'community_updates',
    'title': '社区更新',
    'topics': [{'title': '社区动态', 'topic': 'community-update'}]},
    {   'description': '安全会议、活动与培训信息。',
    'slug': 'security_events',
    'title': '安全活动',
    'topics': [{'title': '会议与培训', 'topic': 'security-event'}]},
    {   'description': '安全企业投融资与战略合作动态。',
    'labels': [   {'label': 'funding', 'title': '融资快讯'},
                  {'label': 'merger', 'title': '并购整合'}],
    'slug': 'security_funding',
    'title': '安全融资'},
    {   'description': '全球威胁情报、攻击态势与应急提示。',
    'slug': 'threat_intelligence',
    'title': '威胁情报',
    'topics': [   {'title': '情报快报', 'topic': 'threat-intel'},
                  {'title': '事件通报', 'topic': 'incident'}]},
    {   'description': '研究报告、漏洞分析与技术白皮书。',
    'slug': 'security_research',
    'title': '安全研究',
    'topics': [{'title': '研究洞察', 'topic': 'research'}]},
    {   'description': '安全工具、平台与产品的更新动态。',
    'labels': [   {'label': 'tooling', 'title': '工具更新'},
                  {'label': 'product', 'title': '产品发布'}],
    'slug': 'tool_updates',
    'title': '工具与产品'},
]

__all__ = ["HOME_SECTIONS"]
